### ISSUE TITLE
Unable to render custom ko templates on ojThematicMap

### ISSUE THREAD

**Issue by shimizust** [oracle/oraclejet#14]
Hi there,

I was trying to render simple custom knockout templates over a map area, similar to this Cookbook example: [](http://www.oracle.com/webfolder/technetwork/jet/jetCookbook.html?component=thematicMap&demo=template)

However, if the ojComponent inside the provided template is switched from ojChart to a non-data visualization component (say ojButton) or a simple:

```
<div data-bind='text: mytext'></div>
```

I get the following error: 

```
Message: oj.Components.getWidgetConstructor(...) is not a function
    at _GetDvtComponent (http://localhost:8000/js/libs/oj/v2.1.0/debug/ojdvt-base.js:1231:61)
    at ._GetDvtComponent (http://localhost:8000/js/libs/jquery/jqueryui-amd-1.12.0/widget.js:132:25)
    at templateHandlerFunc (http://localhost:8000/js/libs/oj/v2.1.0/debug/ojthematicmap.js:563:28)
    at DvtThematicMapJsonParser.ParseDataLayers (http://localhost:8000/js/libs/oj/v2.1.0/debug/internal-deps/dvt/DvtThematicMap.js:7521:23)
    at DvtThematicMapJsonParser._parseAreaLayers (http://localhost:8000/js/libs/oj/v2.1.0/debug/internal-deps/dvt/DvtThematicMap.js:7349:12)
    at DvtThematicMapJsonParser.parse (http://localhost:8000/js/libs/oj/v2.1.0/debug/internal-deps/dvt/DvtThematicMap.js:7246:8)
    at dvt.ThematicMap.SetOptions (http://localhost:8000/js/libs/oj/v2.1.0/debug/internal-deps/dvt/DvtThematicMap.js:402:10)
    at dvt.PanZoomComponent.render (http://localhost:8000/js/libs/oj/v2.1.0/debug/internal-deps/dvt/DvtPanZoomCanvas.js:3483:12)
    at _renderComponent (http://localhost:8000/js/libs/oj/v2.1.0/debug/ojdvt-base.js:1505:21)
    at ._renderComponent (http://localhost:8000/js/libs/jquery/jqueryui-amd-1.12.0/widget.js:132:25)
```

Ideally, any sort of knockout component would be able to be rendered, not just oracle jet DVT components. The knockout template also seems limited to only a single DVT component. Is there a workaround for this? Or is it just a limitation of the map component?

Thanks

**Comment by daibolical** [comment]
No, unfortunately the data stamped knockout templates like those used for ojDiagram nodes and ojThematicMap area and point data layers are limited to supporting a single DVT.  We render everything for DVTs using SVG and because of our IE11 support we can't use SVG foreignObjects to render any arbitrary HTML. We document the limitation in our JSDoc [here](http://jet.us.oracle.com/2.2.0/jsdocs/oj.ojThematicMap.html#areaLayers.areaDataLayer.template), but I'll update it to be more explicit about the number of DVTs supported in the template.

**Comment by daibolical** [comment]
Oh actually if you don't care about IE11 or are able to provide alternative content in SVG via a switch element, we also support stamping out an SVG element within our knockout template as well where you can provide the HTML content inside a <foreignObject> yourself.

**Comment by daibolical** [comment]
Actually if you don't care about IE11, we also support SVG in our template so the following will work if you put this in your ko template:
`<svg width="400px" height="300px" viewBox="0 0 400 300"
     xmlns="http://www.w3.org/2000/svg">
    <foreignObject width="70" height="30">
      <button type="button">Click Me!</button>
    </foreignObject>
</svg>`

I think you should be able to use a <switch> element within the <svg> to provide alternate content for IE11 according to [this](https://developer.mozilla.org/en/docs/Web/SVG/Element/foreignObject) which I briefly tried, but couldn't get to work just using that sample.
