### ISSUE TITLE
oj-data-grid refresh after edit is throwing error

### ISSUE THREAD

**Issue by ciancu** [oracle/oraclejet#62]
This issue is reproduced in 8.2.0, but not in 8.1.0
Browser: Chrome, Version 81.0.4044.113 (Official Build) (64-bit)
OS: Windows 10 Pro

On any of the samples from cookbook where editable cells are enabled, e.g. https://www.oracle.com/webfolder/technetwork/jet/jetCookbook.html?component=dataGrid&demo=dataProviderGrid

I've added a button to execute the data grid refresh function, e.g. $("#datagrid")[0].refresh();

If I press the Refresh button after any edit on the data grid, I get the following error:
`Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. at a._destroyEditableClone (https://static.oracle.com/cdn/jet/v8.2.0/default/js/min/ojdatagrid.js:7:190174) at a.resetInternal (https://static.oracle.com/cdn/jet/v8.2.0/default/js/min/ojdatagrid.js:7:31147) at a.refresh (https://static.oracle.com/cdn/jet/v8.2.0/default/js/min/ojdatagrid.js:7:27747) at e.<computed>.<computed>._possiblyRenderOrRefresh (https://static.oracle.com/cdn/jet/v8.2.0/default/js/min/ojdatagrid.js:7:329044) at e.<computed>.<computed>._possiblyRenderOrRefresh (https://static.oracle.com/cdn/jet/v8.2.0/default/js/min/oj3rdpartybundle.js:52:1082) at e.<computed>.<computed>.refresh (https://static.oracle.com/cdn/jet/v8.2.0/default/js/min/ojdatagrid.js:7:313353) at e.<computed>.<computed>.refresh (https://static.oracle.com/cdn/jet/v8.2.0/default/js/min/oj3rdpartybundle.js:52:1082) at HTMLElement.<anonymous> (https://static.oracle.com/cdn/jet/v8.2.0/default/js/min/oj3rdpartybundle.js:52:2044) at Function.each (https://static.oracle.com/cdn/jet/v8.2.0/default/js/min/oj3rdpartybundle.js:32:2758) at w.fn.init.each (https://static.oracle.com/cdn/jet/v8.2.0/default/js/min/oj3rdpartybundle.js:32:1401)
`
It seems that the issue comes from the function:
DvtDataGrid.prototype._destroyEditableClone

**Comment by ciancu** [comment]
After investigating a bit more, I've found this on the internet and it seems it matches the scenario:
Essentially, when a node is removed from the DOM tree, it fires a blur event (and before a focusout event too). 

So, when you call removeChild, the blur event is fired again, but this time textarea still has its parentNode defined, but textarea isn't among its parent's children anymore! 
https://stackoverflow.com/questions/21926083/failed-to-execute-removechild-on-node

**Comment by peppertech** [comment]
Thanks @ciancu, I've filed an internal bug for this as well and we're looking into a fix for it.
