### ISSUE TITLE
ojet add sass fails with HTTP error 404 Not Found

### ISSUE THREAD

**Issue by darshanputtaswamy** [oracle/oraclejet#75]
$ ojet add sass
Performing 'npm install node-sass'
Executing: cmd.exe /s /c npm install node-sass@4.13.0 --save-dev=true
npm
 WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> node-sass@4.13.0 install D:\Projects\MARC\test\JET-Theme-Builder\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-83_binding.node

Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-83_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.13.0 postinstall D:\Projects\MARC\test\JET-Theme-Builder\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe D:\Projects\MARC\test\JET-Theme-Builder\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose 
--libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=

gyp
 info it worked if it ends with ok

gyp
verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\Projects\\MARC\\test\\JET-Theme-Builder\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]

gyp info using node-gyp@3.8.0
gyp info using node@14.17.3 | win32 | x64
gyp verb command rebuild []

gyp
 verb command clean []

gyp verb clean removing "build" directory

gyp
 verb command configure []

gyp verb check python checking for Python executable "python2" in the PATH

gyp
 verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Projects\MARC\test\JET-Theme-Builder\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Projects\MARC\test\JET-Theme-Builder\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Projects\MARC\test\JET-Theme-Builder\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Projects\MARC\test\JET-Theme-Builder\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Projects\MARC\test\JET-Theme-Builder\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Projects\MARC\test\JET-Theme-Builder\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Projects\MARC\test\JET-Theme-Builder\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Projects\MARC\test\JET-Theme-Builder\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Projects\MARC\test\JET-Theme-Builder\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Projects\MARC\test\JET-Theme-Builder\node_modules\which\which.js:89:16

gyp verb `which` failed     at D:\Projects\MARC\test\JET-Theme-Builder\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Projects\MARC\test\JET-Theme-Builder\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH

gyp verb
 `which` succeeded python C:\Python39\python.EXE

gyp ERR! configure error 

gyp ERR! stack Error: Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:319:12)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp
ERR! stack     at maybeClose (internal/child_process.js:1055:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Projects\\MARC\\test\\JET-Theme-Builder\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\Projects\MARC\test\JET-Theme-Builder\node_modules\node-sass
gyp ERR! node -v v14.17.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Build failed with error code: 1

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm
ERR! node-sass@4.13.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.13.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dpp\AppData\Roaming\npm-cache\_logs\2021-07-09T16_21_49_046Z-debug.log

child process exited with code: 1
(node:11920) UnhandledPromiseRejectionWarning: undefined
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11920) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:11920) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by peppertech** [comment]
You're a few days ahead of the game on this one.  While the NPM packages for v11 have been released (about 3 hours ago) we have not actually done a GA release of JET v11 to the public.  That will be happening at some point on Monday the 12th of July.  The website update will contain the updated file that you are trying to download.  Right now, you are getting the v10.1.0 release of the ThemeBuilder app and trying to run it with JET v11.

Please hang on for a few more days and then you should be golden.

**Comment by peppertech** [comment]
This should be working for you now if you want to start from the beginning with downloading the Theme Builder application. Sorry for the troubles.
